# specify which environment to use

development:
  adapter: sqlite3
  database: db/garage-development

test:
  adapter: sqlite3
  database: db/garage-test

production:
  adapter: sqlite3
  database: db/garage-production
